apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinity-hard
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: yadhuvamsi/simple-webapplication:latest
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: labelname
                operator: In
                values:
                - nodeselector
