apiVersion: apps/v1
kind: Deployment
metadata:
  name: noexecute
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: yadhuvamsi/simple-webapplication:latest
        ports:
        - containerPort: 80
      tolerations:
      -  key: "labelname"
         operator: "Equal"
         value: "taint"
         effect: "NoExecute"
